version: '3.8'

services:
  csharp-dependency-statistic:
    build:
      context: .
      dockerfile: Dockerfile
    image: csuzdibence/csharp-dependency-statistic:latest
    container_name: csharp_dependency_statistic_app
    volumes:
      - ${SOLUTION_PATH_FOLDER}:/app/solution
    working_dir: /app
    restart: unless-stopped